# Generated by Django 4.1.7 on 2023-03-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_cloth', models.CharField(max_length=200)),
                ('path_to_image', models.CharField(max_length=200)),
                ('size', models.CharField(choices=[('LARGE', 'Large'), ('MEDIUM', 'Medium'), ('SMALL', 'Small')], max_length=6)),
            ],
        ),
    ]
