# Generated by Django 4.1.7 on 2023-04-26 12:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_cloth', models.TextField(max_length=200)),
                ('path_to_image', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=300), size=None)),
                ('price', models.FloatField(blank=True)),
                ('size', models.TextField(choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')], max_length=6)),
                ('in_stock', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
