# Generated by Django 4.1.7 on 2023-06-01 11:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_cloth', models.TextField(max_length=50)),
                ('path_to_image', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=200), size=None)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('size', models.TextField(choices=[('LARGE', 'Large'), ('MEDIUM', 'Medium'), ('SMALL', 'Small')], max_length=6)),
            ],
        ),
    ]
