# Generated by Django 4.1.7 on 2023-03-22 14:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clothes_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='path_to_image',
        ),
        migrations.AddField(
            model_name='cloth',
            name='path_to_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=1, size=None),
            preserve_default=False,
        ),
    ]
