# Generated by Django 4.1.7 on 2023-06-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clothes_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloth',
            name='in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloth',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
