# Generated by Django 4.1.7 on 2023-06-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clothes_store', '0002_cloth_discount_cloth_in_stock_cloth_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='discount',
        ),
        migrations.AddField(
            model_name='cloth',
            name='price_with_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
