# Generated by Django 4.1.7 on 2023-03-22 14:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clothes_store', '0002_remove_cloth_path_to_image_cloth_path_to_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='path_to_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
