# Generated by Django 4.1.7 on 2023-03-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clothes_store', '0003_alter_cloth_path_to_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='path_to_images',
            new_name='path_to_image',
        ),
    ]
