# Generated by Django 4.1.7 on 2023-03-22 14:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clothes_store', '0004_rename_path_to_images_cloth_path_to_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='path_to_image',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None), size=None),
        ),
    ]
